package com.Desyfadliaty.budayasunda;

import android.app.Activity;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;

public class Kamus extends Activity {
   
	String indonesia[] = {"ganteng","lari","baru","muda","saudara","mendung","sehat","cepat","gugup","gerah",
			"abu",
			"abu Rokok",
			"ada",
			"adalah",
			"adik",
			"air",
			"ajar",
			"akan",
			"akan",
			"alis",
			"anak",
			"anak Kakak",
			"anak Kecil",
			"aneh",
			"angsa", 
			"anjing", 
			"apa",
			"api",
			"asam",
			"asin",
			"asin Sekali",
			"atas",
			"ayam",
			"Sahabat",
			"Sahabat Dekat",
			"Sakit", 
			"Salah", 
			"Sama",
			"Sambal", 
			"Sambat", 
			"Sambit", 
			"Sampah", 
			"Sana", 
			"Sandal", 
			"Sandal Jepit", 
			"Sandal ber-hak", 
			"Sapu Ijuk", 
			"Sapu Lidi", 
			"Saring", 
			"Saringan", 
			"Satu", 
			"Satu Juta",
			"Satu Ribu", 
			"Saudara",
			"Saya",
			"Sayang", 
			"Sayap",
			"Sebagian",
			"Sebaliknya",
			"Sebelah", 
			"Sebelahan", 
			"Sebelas", 
			"Sebut", 
			"Sedang", 
			"Sedang sakit", 
			"Sedih", 
			"Sehat", 
			"Sekarang", 
			"Selangkangan", 
			"Selokan",
			"Semacam", 
			"Semangat", 
			"Sembilan",
			"Sempit",
			"Semua",
			"Semut", 
			"Senang",
			"Sepatu",
			"Sepuluh", 
			"Sepuluh Ribu", 
			"Serak", 
			"Seratus", 
			"Seratus Ribu", 
			"Seribu", 
			"Siang", 
			"Siapa", 
			"Silakan", 
			"Silau", 
			"Singlet", 
			"Sini",
			"Sisa", 
			"Sisi",
			"Sobek",
			"Sore",
			"Suami", 
			"Sudah", 
			"Sudah Lama tinggal di sini", 
			"Sudah makan belom",
			"Sungai",
			"Susah",
			"Tadi",
			"Tahi Lalat",
			"Takut", 
			"Tampar", 
			"Tanah", 
			"Tanah Lapang", 
			"Tanda",
			"Tangan", 
			"Tangga Bambu", 
			"Tapian",
			"Tau", 
			"Tegel", 
			"Teguh", 
			"Telapak Tangan", 
			"Telat", 
			"Telinga", 
			"Teman", 
			"Temu", 
			"Tentang", 
			"Teras", 
			"Terbaha-bahak",
			"Terbaik", 
			"Tergoda", 
			"Teringat-ingat", 
			"Terkam", 
			"Terkena Petir", 
			"Termasuk",
			"Tersengat Listrik",
			"Tersenyum", 
			"Tersesat", 
			"Tertawa",
			"Tiang",
			"Tidak",
			"Tidak Akan", 
			"Tidak Mau",
			"Tidak Tau",
			"Tidur",
			"Tiga",
			"Tikus", 
			"Tinggal dimana",
			"Tinggalnya dimana", 
			"Tinggi (Tempat )",
			"Tinggi",
			"Tiri",
			"Tolong", 
			"Topi",
			"Tua",
			"Tujuh", 
			"Tusuk",
			"Uang",
			"Uang Logam", 
			"Uban",
			"Udel",
			"Ular",
			"Ulat",
			"Ulekan", 
			"Untuk (Kegunaan)",
			"Untuk",
			"Usia",
			"Wajah",
			"Wanita", 
			"Waria",
			"Warna",
			"Ya",
			"Yang", 
			"Yang dipakai", 
			"Saya", 
			"Kamu",
			"Dia",
			"Kami",
			"Kalian", 
			"Pergi",
			"Datang",
			"Bangun Tidur",
			"Tidur",
			"Makan",
			"Minum",
			"ngantuk", 
			"lapar",
			"dahaga",
			"dingin",
			"ngilu",
			"gatal",
			"geli",
			"senang", 
			"sedih",
			"bahagia", 
			"kebahagiaan", 
			"gembira",
			"bergembira", 
			"sayang",
			"ingat",
			"mengingat", 
			"lupa",
			"susah", 
			"mudah",
			"merasa",
			"Sekarang", 
			"Kemarin", 
			"Kemarin Lusa", 
			"Besok", 
			"Besok Lusa",
			"Tadi", 
			"Barusan", 
			"Pagi", 
			"Siang", 
			"Sore",
			"Malam", 
			"Pagi Buta",

	};
   String sunda[] = {"Kasep","Lumpat","Anyar","Anom","Baraya","Ceudeum","Damang","Enggal","Geumpeur","Hareudang",
		   "Kekebul",
		   "Calacah",
		   "Aya",
		   "Nyaeta",
		   "Rai, Adi, Pun Adi",
		   "Cai",
		   "Wuruk, Atik ; Belajar = Diajar ; Ajaran = Wurukan, Atikan",
		   "Bade, Arek",
		   "Bakal",
		   "Halis",
		   "Budak, Murangkalih",
		   "Alo",
		   "Budak Leutik, Murangkalih",
		   "Aheng",
		   "Soang",
		   "Gogog",
		   "Naon ; Mau Apa = Bade Naon, Erek Naon",
		   "Seuneu",
		   "Haseum, Asem (Benda)",
		   "Asin",
		   "Molelel",
		   "Luhur",
		   "Hayam",
		   "Sobat",
		   "Sobat Dalit",
		   "udur",
		   "Lepat, Teu Leres",
		   "Sami, Sarua ; Sesama = Papada",
		   "Sambel",
		   "Nyambat",
		   "Sabet, Kadek",
		   "Runtah",
		   "Ditu ; Sebelah Sana = Palih Ditu",
		   "Sendal",
		   "Sendal Capit",
		   "Kelom",
		   "Sapu Injuk",
		   "Nyere",
		   "Ayak",
		   "Ayakan",
		   "Hiji",
		   "Sajuta",
		   "Sarebu",
		   "Baraya, Dulur",
		   "Abdi, Kuring, Urang, Uing, Aing",
		   "nyaah",
		   "Jangjang",
		   "Sapalih, Sawareh",
		   "Sabalikna",
		   "Sapalih, Sabeulah",
		   "Gigireun",
		   "Sabelas, sawelas",
		   "Nyebat ;Menyebutkeun = Nyebatkeun",
		   "Nuju",
		   "udur",
		   "tunggara",
		   "Walagri",
		   "Ayeuna",
		   "Palangkakan",
		   "Solokan",
		   "Sarupaning",
		   "Sumanget",
		   "Salapan",
		   "Heureut",
		   "Sadaya, Kabeh",
		   "Sireum",
		   "bungah",
		   "Sapatu",
		   "Sepuluh",
		   "Sapuluh Rebu",
		   "Peura",
		   "Saratu",
		   "Saratus Rebu",
		   "Sarebu",
		   "Siang, Beurang",
		   "Saha",
		   "Mangga",
		   "Serab",
		   "Kaos Sangsang",
		   "Dieu ; Sebelah Sini = Palih Dieu",
		   "Sesa ; Menyisakan = Nyesakeun",
		   "Gigir",
		   "Soweh, Sowek",
		   "Sonten",
		   "Caroge, Salaki",
		   "Parantos, Atos, Enggeus",
		   "Tos lami linggih di dieu",
		   "Tos tuang teu acan",
		   "Susukan",
		   "Sesah, Hese",
		   "Tadi",
		   "Karang",
		   "Sieun",
		   "Cabok, Gampleng, Tampiling",
		   "Taneuh",
		   "Tegalan",
		   "Tanda ; Menandakan = Nandakeun",
		   "Panangan, Leungeun",
		   "Taraje",
		   "Nyiru",
		   "Terang, Uninga, Nyaho",
		   "Tehel",
		   "Panceg",
		   "Dampal Leungeun",
		   "Laat",
		   "Cepil, Ceuli",
		   "Rerencangan, Babaturan",
		   "Pendak, manggih ; Ketemu = Kapendak, Kapanggih",
		   "Perkawis",
		   "Tepas",
		   "Nyakakak, Ngabarakatak",
		   "Nyongcolang",
		   "Kagoda",
		   "Kasuat-suat",
		   "Kerekeb, Gabrug",
		   "Kabentar Gelap",
		   "Kalebet, Kaasup",
		   "Kasetrum",
		   "Imut",
		   "Kasasab",
		   "Seuri",
		   "Tihang",
		   "Henteu",
		   "Moal",
		   "Alim, Teu Hoyong, Embung",
		   "Duka, Teu Terang, Teuing",
		   "Kulem, Bobo, Sare (bahasa kasar)",
		   "Tilu",
		   "Beurit",
		   "Linggih dimana",
		   "Linggih Timanten",
		   "Luhur",
		   "Jangkung",
		   "Tere",
		   "Bantos, Tulung ; Pertolongan = Bantosan, Pitulung",
		   "Kerepus, Topi",
		   "Sepuh, Kolot",
		   "Tujuh",
		   "Tojos",
		   "Artos, Duit",
		   "Receh, Kencring",
		   "Huis, Salatu",
		   "Bujal",
		   "Oray",
		   "Hileud",
		   "Mutu",
		   "Untuk (Kegunaan) = Paranti",
		   "Pikeun, Kanggo, Jang",
		   "Usia = Yuswa, Umur",
		   "Raray, Beungeut",
		   "Mojang, Istri, Awewe",
		   "Banci, Bencong",
		   "Kelir",
		   "Muhun, Heueuh",
		   "Anu",
		   "Anu Dianggo, Nu Dipake",
		   "Abdi, Kuring, Urang (bahasa kasar)",
		   "Anjeun, Maneh (bahasa kasar)",
		   "Manehna",
		   "Urang",
		   "Maranehna",
		   "Angkat, Mios, Indit (bahasa kasar)",
		   "Dongkap, Sumping, Mulang, Balik (bahasa kasar)",
		   "Gugah, Hudang (bahasa kasar)",
		   "Kulem, Bobo, Sare (bahasa kasar)",
		   "Tuang (untuk orang lain) , Neda (untuk diri sendiri), Dahar (bahasa kasar)",
		   "Eueut, Nginum (bahasa kasar)",
		   "tunduh",
		   "lapar",
		   "Haus",
		   "tiris",
		   "linu",
		   "ateul",
		   "getek",
		   "bungah",
		   "lara",
		   "bagja",
		   "kabagjaan",
		   "gumbira",
		   "galumbira",
		   "nyaah",
		   "emut/inget",
		   "ngemut/mieling",
		   "hilap",
		   "sesah/hese",
		   "gampil/babari/gampang",
		   "rumaos",
		   "Ayeuna",
		   "Kamari",
		   "Mangkukna",
		   "Enjing, Isuk (bahasa kasar)",
		   "Pageto",
		   "Nembe",
		   "Bieu",
		   "Enjing-enjing / Isuk-isuk",
		   "Siang / Beurang",
		   "Sonten",
		   "Wengi / Peuting",
		   "Janari",
	   
		   
   };
	
   @Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.kamus);
		
		   	
			
		
		Button btn = (Button) findViewById(R.id.button1);
		
		btn.setOnClickListener(new OnClickListener() {
			
			@Override
			public void onClick(View arg0) {
				// TODO Auto-generated method stub
				EditText et1 = (EditText) findViewById(R.id.editText1);
				TextView et2 = (TextView) findViewById(R.id.textView3);
				

				for (int i=0; i<indonesia.length;i++){
					if(indonesia[i].toLowerCase().equals(et1.getText().toString().toLowerCase())){
						et2.setText(sunda[i]);
					}
				}
			}
		});
		
	}
}


